name: Deploy to ECR and EC2

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: 체크아웃
      uses: actions/checkout@v3

    - name: JDK 17 설치
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: gradlew 실행 권한 부여
      run: chmod +x ./gradlew

    - name: Gradle로 빌드 (테스트 제외)
      run: ./gradlew build -x test

    - name: AWS 자격 증명 설정
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Amazon ECR 로그인
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Docker 이미지 빌드 및 ECR로 푸시
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/hufs-dns-server:latest .
        docker push ${{ steps.login-ecr.outputs.registry }}/hufs-dns-server:latest

    # 자동 배포 단계
    - name: EC2에 배포 (SSH 접속)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}      
        username: ubuntu                  
        key: ${{ secrets.EC2_SSH_KEY }}    
        script: |
          # 1. 로그인 & 이미지 받기
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 365202715959.dkr.ecr.ap-northeast-2.amazonaws.com
          docker pull 365202715959.dkr.ecr.ap-northeast-2.amazonaws.com/hufs-dns-server:latest
          
          # 2. 기존 백엔드 컨테이너 삭제
          docker stop my-server || true
          docker rm my-server || true
          
          # 3. 80번 포트 강제 점유 해제
          sudo fuser -k 80/tcp || true
          
          # 4. 새 컨테이너 실행
          docker run -d -p 80:8080 \
            -e SPRING_DATASOURCE_URL='${{ secrets.DB_URL }}' \
            -e SPRING_DATASOURCE_USERNAME='${{ secrets.DB_USERNAME }}' \
            -e SPRING_DATASOURCE_PASSWORD='${{ secrets.DB_PASSWORD }}' \
            -e CLOUDFLARE_API_TOKEN='${{ secrets.CLOUDFLARE_API_TOKEN }}' \
            -e CLOUDFLARE_ZONE_ID='${{ secrets.CLOUDFLARE_ZONE_ID }}' \
            -e CLOUDFLARE_BASE_URL='https://api.cloudflare.com/client/v4' \
            -e SERVER_FORWARD_HEADERS_STRATEGY=native \
            -e SERVER_TOMCAT_REMOTEIP_PROTOCOL_HEADER=X-Forwarded-Proto \
            -e SERVER_TOMCAT_REMOTEIP_REMOTE_IP_HEADER=X-Forwarded-For \
            -e SERVER_TOMCAT_REMOTEIP_INTERNAL_PROXIES='.*' \
            --name my-server 365202715959.dkr.ecr.ap-northeast-2.amazonaws.com/hufs-dns-server:latest
          
          # 5. 미사용 이미지 정리
          docker image prune -f
